# Generated by Django 5.2.7 on 2025-10-08 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SH Parts', max_length=255, verbose_name='اسم الشركة')),
                ('company_name_en', models.CharField(default='SH Parts', max_length=255, verbose_name='اسم الشركة بالإنجليزية')),
                ('currency', models.CharField(choices=[('EGP', 'الجنيه المصري - Egyptian Pound (EGP)'), ('SAR', 'الريال السعودي - Saudi Riyal (SAR)'), ('AED', 'الدرهم الإماراتي - UAE Dirham (AED)'), ('USD', 'الدولار الأمريكي - US Dollar (USD)'), ('EUR', 'اليورو - Euro (EUR)')], default='EGP', max_length=3, verbose_name='العملة')),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة الافتراضية')),
                ('timezone', models.CharField(choices=[('Africa/Cairo', 'القاهرة (مصر)'), ('Asia/Riyadh', 'الرياض (السعودية)'), ('Asia/Dubai', 'دبي (الإمارات)'), ('UTC', 'UTC')], default='Africa/Cairo', max_length=50, verbose_name='المنطقة الزمنية')),
                ('tax_enabled', models.BooleanField(default=True, verbose_name='تفعيل الضرائب')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14.0, help_text='نسبة الضريبة المضافة (مصر: 14%، السعودية: 15%)', max_digits=5, verbose_name='نسبة الضريبة (%)')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(default='القاهرة', max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='التنبيه عندما تقل الكمية عن هذا الرقم', verbose_name='حد تنبيه المخزون المنخفض')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بالمخزون السالب')),
                ('require_customer_for_sale', models.BooleanField(default=True, verbose_name='إلزامية العميل في المبيعات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
