# Generated by Django 5.2.7 on 2025-10-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=50, unique=True, verbose_name='SKU')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_EXCELLENT', 'Used - Excellent'), ('USED_GOOD', 'Used - Good'), ('USED_FAIR', 'Used - Fair'), ('REFURBISHED', 'Refurbished')], max_length=20, verbose_name='condition')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='minimum quantity')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='selling price')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='barcode')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_items', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='cars.part', verbose_name='part')),
                ('vehicle_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_parts', to='cars.vehicle', verbose_name='source vehicle')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory_items/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'inventory item image',
                'verbose_name_plural': 'inventory item images',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100, verbose_name='warehouse')),
                ('aisle', models.CharField(blank=True, max_length=20, verbose_name='aisle')),
                ('shelf', models.CharField(blank=True, max_length=20, verbose_name='shelf')),
                ('bin', models.CharField(blank=True, max_length=20, verbose_name='bin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'warehouse location',
                'verbose_name_plural': 'warehouse locations',
                'ordering': ['warehouse', 'aisle', 'shelf', 'bin'],
                'unique_together': {('warehouse', 'aisle', 'shelf', 'bin')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], max_length=20, verbose_name='movement type')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='item')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.warehouselocation', verbose_name='from location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.warehouselocation', verbose_name='to location')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.warehouselocation', verbose_name='location'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status'], name='inventory_i_status_77888d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['part', 'condition'], name='inventory_i_part_id_667923_idx'),
        ),
    ]
