# Generated by Django 5.2.7 on 2025-10-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='report name')),
                ('report_type', models.CharField(choices=[('INVENTORY_VALUATION', 'Inventory Valuation'), ('SALES_SUMMARY', 'Sales Summary'), ('SALES_BY_PART', 'Sales by Part'), ('SALES_BY_CUSTOMER', 'Sales by Customer'), ('CUSTOMER_DEBT', 'Customer Debt'), ('STOCK_MOVEMENT', 'Stock Movement'), ('LOW_STOCK', 'Low Stock Alert'), ('PROFIT_MARGIN', 'Profit Margin Analysis'), ('VEHICLE_INTAKE', 'Vehicle Intake Report'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='report type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='columns')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='scheduled')),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, verbose_name='schedule frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'saved report',
                'verbose_name_plural': 'saved reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='report type')),
                ('parameters', models.JSONField(default=dict, verbose_name='parameters')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='file path')),
                ('file_format', models.CharField(max_length=10, verbose_name='file format')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='executed by')),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.savedreport', verbose_name='saved report')),
            ],
            options={
                'verbose_name': 'report execution',
                'verbose_name_plural': 'report executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
