# Generated by Django 5.2.7 on 2025-10-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='make name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='make name (Arabic)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='car_makes/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'car make',
                'verbose_name_plural': 'car makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='model name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='model name (Arabic)')),
                ('year_start', models.IntegerField(verbose_name='production start year')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='production end year')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='body type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carmake', verbose_name='make')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'car models',
                'ordering': ['make', 'name'],
                'unique_together': {('make', 'name', 'year_start')},
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='category name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon class')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cars.partcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'part category',
                'verbose_name_plural': 'part categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='part name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='part name (Arabic)')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='part number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('default_image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='default image')),
                ('is_universal', models.BooleanField(default=False, verbose_name='universal part')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('compatible_models', models.ManyToManyField(blank=True, related_name='compatible_parts', to='cars.carmodel', verbose_name='compatible models')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='cars.partcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('year', models.IntegerField(verbose_name='year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='mileage')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('SALVAGE', 'Salvage')], max_length=20, verbose_name='condition')),
                ('intake_date', models.DateTimeField(auto_now_add=True, verbose_name='intake date')),
                ('intake_notes', models.TextField(blank=True, verbose_name='intake notes')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase price')),
                ('is_dismantled', models.BooleanField(default=False, verbose_name='dismantled')),
                ('dismantled_date', models.DateTimeField(blank=True, null=True, verbose_name='dismantled date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmake', verbose_name='make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel', verbose_name='model')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='received by')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-intake_date'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle photo',
                'verbose_name_plural': 'vehicle photos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
